/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Drones API
 * OpenAPI spec version: v1
 */
import type {
  AuthResponse,
  CategoryResponse,
  CreateCategoryRequest,
  CreateDispatchRequest,
  CreateDroneRequest,
  CreateOrderRequest,
  CreateProductRequest,
  CreateRestaurantRequest,
  CreateReviewRequest,
  DispatchResponse,
  DroneResponse,
  ForgotPasswordRequest,
  LoginRequest,
  MaintenanceLogResponse,
  MessageResponse,
  OrderResponse,
  PatchIdParams,
  ProductResponse,
  RefreshTokenRequest,
  RegisterRequest,
  ResetPasswordRequest,
  RestaurantResponse,
  ReviewResponse,
  UpdateCategoryRequest,
  UpdateDroneRequest,
  UpdateProductRequest,
  UpdateRestaurantRequest,
  UpdateReviewRequest,
  VerifyEmailRequest
} from './model';

export type postApiAuthRegisterResponse200 = {
  data: AuthResponse
  status: 200
}
    
export type postApiAuthRegisterResponseSuccess = (postApiAuthRegisterResponse200) & {
  headers: Headers;
};
;

export type postApiAuthRegisterResponse = (postApiAuthRegisterResponseSuccess)

export const getPostApiAuthRegisterUrl = () => {


  

  return `/api/auth/register`
}

export const postApiAuthRegister = async (registerRequest: RegisterRequest, options?: RequestInit): Promise<postApiAuthRegisterResponse> => {
  
  const res = await fetch(getPostApiAuthRegisterUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      registerRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postApiAuthRegisterResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postApiAuthRegisterResponse
}



export type postApiAuthLoginResponse200 = {
  data: AuthResponse
  status: 200
}
    
export type postApiAuthLoginResponseSuccess = (postApiAuthLoginResponse200) & {
  headers: Headers;
};
;

export type postApiAuthLoginResponse = (postApiAuthLoginResponseSuccess)

export const getPostApiAuthLoginUrl = () => {


  

  return `/api/auth/login`
}

export const postApiAuthLogin = async (loginRequest: LoginRequest, options?: RequestInit): Promise<postApiAuthLoginResponse> => {
  
  const res = await fetch(getPostApiAuthLoginUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      loginRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postApiAuthLoginResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postApiAuthLoginResponse
}



export type postApiAuthRefreshResponse200 = {
  data: AuthResponse
  status: 200
}
    
export type postApiAuthRefreshResponseSuccess = (postApiAuthRefreshResponse200) & {
  headers: Headers;
};
;

export type postApiAuthRefreshResponse = (postApiAuthRefreshResponseSuccess)

export const getPostApiAuthRefreshUrl = () => {


  

  return `/api/auth/refresh`
}

export const postApiAuthRefresh = async (refreshTokenRequest: RefreshTokenRequest, options?: RequestInit): Promise<postApiAuthRefreshResponse> => {
  
  const res = await fetch(getPostApiAuthRefreshUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      refreshTokenRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postApiAuthRefreshResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postApiAuthRefreshResponse
}



export type postApiAuthRevokeResponse200 = {
  data: MessageResponse
  status: 200
}
    
export type postApiAuthRevokeResponseSuccess = (postApiAuthRevokeResponse200) & {
  headers: Headers;
};
;

export type postApiAuthRevokeResponse = (postApiAuthRevokeResponseSuccess)

export const getPostApiAuthRevokeUrl = () => {


  

  return `/api/auth/revoke`
}

export const postApiAuthRevoke = async (refreshTokenRequest: RefreshTokenRequest, options?: RequestInit): Promise<postApiAuthRevokeResponse> => {
  
  const res = await fetch(getPostApiAuthRevokeUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      refreshTokenRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postApiAuthRevokeResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postApiAuthRevokeResponse
}



export type postApiAuthVerifyEmailResponse200 = {
  data: MessageResponse
  status: 200
}
    
export type postApiAuthVerifyEmailResponseSuccess = (postApiAuthVerifyEmailResponse200) & {
  headers: Headers;
};
;

export type postApiAuthVerifyEmailResponse = (postApiAuthVerifyEmailResponseSuccess)

export const getPostApiAuthVerifyEmailUrl = () => {


  

  return `/api/auth/verify-email`
}

export const postApiAuthVerifyEmail = async (verifyEmailRequest: VerifyEmailRequest, options?: RequestInit): Promise<postApiAuthVerifyEmailResponse> => {
  
  const res = await fetch(getPostApiAuthVerifyEmailUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      verifyEmailRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postApiAuthVerifyEmailResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postApiAuthVerifyEmailResponse
}



export type postApiAuthResendVerificationResponse200 = {
  data: MessageResponse
  status: 200
}
    
export type postApiAuthResendVerificationResponseSuccess = (postApiAuthResendVerificationResponse200) & {
  headers: Headers;
};
;

export type postApiAuthResendVerificationResponse = (postApiAuthResendVerificationResponseSuccess)

export const getPostApiAuthResendVerificationUrl = () => {


  

  return `/api/auth/resend-verification`
}

export const postApiAuthResendVerification = async (forgotPasswordRequest: ForgotPasswordRequest, options?: RequestInit): Promise<postApiAuthResendVerificationResponse> => {
  
  const res = await fetch(getPostApiAuthResendVerificationUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      forgotPasswordRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postApiAuthResendVerificationResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postApiAuthResendVerificationResponse
}



export type postApiAuthForgotPasswordResponse200 = {
  data: MessageResponse
  status: 200
}
    
export type postApiAuthForgotPasswordResponseSuccess = (postApiAuthForgotPasswordResponse200) & {
  headers: Headers;
};
;

export type postApiAuthForgotPasswordResponse = (postApiAuthForgotPasswordResponseSuccess)

export const getPostApiAuthForgotPasswordUrl = () => {


  

  return `/api/auth/forgot-password`
}

export const postApiAuthForgotPassword = async (forgotPasswordRequest: ForgotPasswordRequest, options?: RequestInit): Promise<postApiAuthForgotPasswordResponse> => {
  
  const res = await fetch(getPostApiAuthForgotPasswordUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      forgotPasswordRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postApiAuthForgotPasswordResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postApiAuthForgotPasswordResponse
}



export type postApiAuthResetPasswordResponse200 = {
  data: MessageResponse
  status: 200
}
    
export type postApiAuthResetPasswordResponseSuccess = (postApiAuthResetPasswordResponse200) & {
  headers: Headers;
};
;

export type postApiAuthResetPasswordResponse = (postApiAuthResetPasswordResponseSuccess)

export const getPostApiAuthResetPasswordUrl = () => {


  

  return `/api/auth/reset-password`
}

export const postApiAuthResetPassword = async (resetPasswordRequest: ResetPasswordRequest, options?: RequestInit): Promise<postApiAuthResetPasswordResponse> => {
  
  const res = await fetch(getPostApiAuthResetPasswordUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      resetPasswordRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postApiAuthResetPasswordResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postApiAuthResetPasswordResponse
}



export type postApiCategoriesResponse200 = {
  data: CategoryResponse
  status: 200
}
    
export type postApiCategoriesResponseSuccess = (postApiCategoriesResponse200) & {
  headers: Headers;
};
;

export type postApiCategoriesResponse = (postApiCategoriesResponseSuccess)

export const getPostApiCategoriesUrl = () => {


  

  return `/api/categories`
}

export const postApiCategories = async (createCategoryRequest: CreateCategoryRequest, options?: RequestInit): Promise<postApiCategoriesResponse> => {
  
  const res = await fetch(getPostApiCategoriesUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createCategoryRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postApiCategoriesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postApiCategoriesResponse
}



export type getApiCategoriesResponse200 = {
  data: CategoryResponse[]
  status: 200
}
    
export type getApiCategoriesResponseSuccess = (getApiCategoriesResponse200) & {
  headers: Headers;
};
;

export type getApiCategoriesResponse = (getApiCategoriesResponseSuccess)

export const getGetApiCategoriesUrl = () => {


  

  return `/api/categories`
}

export const getApiCategories = async ( options?: RequestInit): Promise<getApiCategoriesResponse> => {
  
  const res = await fetch(getGetApiCategoriesUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getApiCategoriesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiCategoriesResponse
}



export type getApiCategoriesIdResponse200 = {
  data: CategoryResponse
  status: 200
}
    
export type getApiCategoriesIdResponseSuccess = (getApiCategoriesIdResponse200) & {
  headers: Headers;
};
;

export type getApiCategoriesIdResponse = (getApiCategoriesIdResponseSuccess)

export const getGetApiCategoriesIdUrl = (id: number,) => {


  

  return `/api/categories/${id}`
}

export const getApiCategoriesId = async (id: number, options?: RequestInit): Promise<getApiCategoriesIdResponse> => {
  
  const res = await fetch(getGetApiCategoriesIdUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getApiCategoriesIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiCategoriesIdResponse
}



export type patchApiCategoriesIdResponse200 = {
  data: CategoryResponse
  status: 200
}
    
export type patchApiCategoriesIdResponseSuccess = (patchApiCategoriesIdResponse200) & {
  headers: Headers;
};
;

export type patchApiCategoriesIdResponse = (patchApiCategoriesIdResponseSuccess)

export const getPatchApiCategoriesIdUrl = (id: number,) => {


  

  return `/api/categories/${id}`
}

export const patchApiCategoriesId = async (id: number,
    updateCategoryRequest: UpdateCategoryRequest, options?: RequestInit): Promise<patchApiCategoriesIdResponse> => {
  
  const res = await fetch(getPatchApiCategoriesIdUrl(id),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateCategoryRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: patchApiCategoriesIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as patchApiCategoriesIdResponse
}



export type deleteApiCategoriesIdResponse200 = {
  data: MessageResponse
  status: 200
}
    
export type deleteApiCategoriesIdResponseSuccess = (deleteApiCategoriesIdResponse200) & {
  headers: Headers;
};
;

export type deleteApiCategoriesIdResponse = (deleteApiCategoriesIdResponseSuccess)

export const getDeleteApiCategoriesIdUrl = (id: number,) => {


  

  return `/api/categories/${id}`
}

export const deleteApiCategoriesId = async (id: number, options?: RequestInit): Promise<deleteApiCategoriesIdResponse> => {
  
  const res = await fetch(getDeleteApiCategoriesIdUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: deleteApiCategoriesIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteApiCategoriesIdResponse
}



export type getApiCategoriesRestaurantRestaurantIdResponse200 = {
  data: CategoryResponse[]
  status: 200
}
    
export type getApiCategoriesRestaurantRestaurantIdResponseSuccess = (getApiCategoriesRestaurantRestaurantIdResponse200) & {
  headers: Headers;
};
;

export type getApiCategoriesRestaurantRestaurantIdResponse = (getApiCategoriesRestaurantRestaurantIdResponseSuccess)

export const getGetApiCategoriesRestaurantRestaurantIdUrl = (restaurantId: string,) => {


  

  return `/api/categories/restaurant/${restaurantId}`
}

export const getApiCategoriesRestaurantRestaurantId = async (restaurantId: string, options?: RequestInit): Promise<getApiCategoriesRestaurantRestaurantIdResponse> => {
  
  const res = await fetch(getGetApiCategoriesRestaurantRestaurantIdUrl(restaurantId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getApiCategoriesRestaurantRestaurantIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiCategoriesRestaurantRestaurantIdResponse
}



export type postApiDispatchesResponse200 = {
  data: DispatchResponse
  status: 200
}
    
export type postApiDispatchesResponseSuccess = (postApiDispatchesResponse200) & {
  headers: Headers;
};
;

export type postApiDispatchesResponse = (postApiDispatchesResponseSuccess)

export const getPostApiDispatchesUrl = () => {


  

  return `/api/dispatches`
}

export const postApiDispatches = async (createDispatchRequest: CreateDispatchRequest, options?: RequestInit): Promise<postApiDispatchesResponse> => {
  
  const res = await fetch(getPostApiDispatchesUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createDispatchRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postApiDispatchesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postApiDispatchesResponse
}



export type getApiDispatchesDispatchIdResponse200 = {
  data: DispatchResponse
  status: 200
}
    
export type getApiDispatchesDispatchIdResponseSuccess = (getApiDispatchesDispatchIdResponse200) & {
  headers: Headers;
};
;

export type getApiDispatchesDispatchIdResponse = (getApiDispatchesDispatchIdResponseSuccess)

export const getGetApiDispatchesDispatchIdUrl = (dispatchId: string,) => {


  

  return `/api/dispatches/${dispatchId}`
}

export const getApiDispatchesDispatchId = async (dispatchId: string, options?: RequestInit): Promise<getApiDispatchesDispatchIdResponse> => {
  
  const res = await fetch(getGetApiDispatchesDispatchIdUrl(dispatchId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getApiDispatchesDispatchIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiDispatchesDispatchIdResponse
}



export type getApiDispatchesOrderOrderIdResponse200 = {
  data: DispatchResponse
  status: 200
}
    
export type getApiDispatchesOrderOrderIdResponseSuccess = (getApiDispatchesOrderOrderIdResponse200) & {
  headers: Headers;
};
;

export type getApiDispatchesOrderOrderIdResponse = (getApiDispatchesOrderOrderIdResponseSuccess)

export const getGetApiDispatchesOrderOrderIdUrl = (orderId: string,) => {


  

  return `/api/dispatches/order/${orderId}`
}

export const getApiDispatchesOrderOrderId = async (orderId: string, options?: RequestInit): Promise<getApiDispatchesOrderOrderIdResponse> => {
  
  const res = await fetch(getGetApiDispatchesOrderOrderIdUrl(orderId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getApiDispatchesOrderOrderIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiDispatchesOrderOrderIdResponse
}



export type patchApiDispatchesDispatchIdStatusResponse200 = {
  data: DispatchResponse
  status: 200
}
    
export type patchApiDispatchesDispatchIdStatusResponseSuccess = (patchApiDispatchesDispatchIdStatusResponse200) & {
  headers: Headers;
};
;

export type patchApiDispatchesDispatchIdStatusResponse = (patchApiDispatchesDispatchIdStatusResponseSuccess)

export const getPatchApiDispatchesDispatchIdStatusUrl = (dispatchId: string,) => {


  

  return `/api/dispatches/${dispatchId}/status`
}

export const patchApiDispatchesDispatchIdStatus = async (dispatchId: string,
    patchApiDispatchesDispatchIdStatusBody: string, options?: RequestInit): Promise<patchApiDispatchesDispatchIdStatusResponse> => {
  
  const res = await fetch(getPatchApiDispatchesDispatchIdStatusUrl(dispatchId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      patchApiDispatchesDispatchIdStatusBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: patchApiDispatchesDispatchIdStatusResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as patchApiDispatchesDispatchIdStatusResponse
}



export type postApiDispatchesDispatchIdSimulateResponse200 = {
  data: MessageResponse
  status: 200
}
    
export type postApiDispatchesDispatchIdSimulateResponseSuccess = (postApiDispatchesDispatchIdSimulateResponse200) & {
  headers: Headers;
};
;

export type postApiDispatchesDispatchIdSimulateResponse = (postApiDispatchesDispatchIdSimulateResponseSuccess)

export const getPostApiDispatchesDispatchIdSimulateUrl = (dispatchId: string,) => {


  

  return `/api/dispatches/${dispatchId}/simulate`
}

export const postApiDispatchesDispatchIdSimulate = async (dispatchId: string, options?: RequestInit): Promise<postApiDispatchesDispatchIdSimulateResponse> => {
  
  const res = await fetch(getPostApiDispatchesDispatchIdSimulateUrl(dispatchId),
  {      
    ...options,
    method: 'POST'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postApiDispatchesDispatchIdSimulateResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postApiDispatchesDispatchIdSimulateResponse
}



export type postApiDronesResponse200 = {
  data: DroneResponse
  status: 200
}
    
export type postApiDronesResponseSuccess = (postApiDronesResponse200) & {
  headers: Headers;
};
;

export type postApiDronesResponse = (postApiDronesResponseSuccess)

export const getPostApiDronesUrl = () => {


  

  return `/api/drones`
}

export const postApiDrones = async (createDroneRequest: CreateDroneRequest, options?: RequestInit): Promise<postApiDronesResponse> => {
  
  const res = await fetch(getPostApiDronesUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createDroneRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postApiDronesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postApiDronesResponse
}



export type getApiDronesResponse200 = {
  data: DroneResponse[]
  status: 200
}
    
export type getApiDronesResponseSuccess = (getApiDronesResponse200) & {
  headers: Headers;
};
;

export type getApiDronesResponse = (getApiDronesResponseSuccess)

export const getGetApiDronesUrl = () => {


  

  return `/api/drones`
}

export const getApiDrones = async ( options?: RequestInit): Promise<getApiDronesResponse> => {
  
  const res = await fetch(getGetApiDronesUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getApiDronesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiDronesResponse
}



export type getApiDronesAvailableResponse200 = {
  data: DroneResponse[]
  status: 200
}
    
export type getApiDronesAvailableResponseSuccess = (getApiDronesAvailableResponse200) & {
  headers: Headers;
};
;

export type getApiDronesAvailableResponse = (getApiDronesAvailableResponseSuccess)

export const getGetApiDronesAvailableUrl = () => {


  

  return `/api/drones/available`
}

export const getApiDronesAvailable = async ( options?: RequestInit): Promise<getApiDronesAvailableResponse> => {
  
  const res = await fetch(getGetApiDronesAvailableUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getApiDronesAvailableResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiDronesAvailableResponse
}



export type getApiDronesDroneIdResponse200 = {
  data: DroneResponse
  status: 200
}
    
export type getApiDronesDroneIdResponseSuccess = (getApiDronesDroneIdResponse200) & {
  headers: Headers;
};
;

export type getApiDronesDroneIdResponse = (getApiDronesDroneIdResponseSuccess)

export const getGetApiDronesDroneIdUrl = (droneId: string,) => {


  

  return `/api/drones/${droneId}`
}

export const getApiDronesDroneId = async (droneId: string, options?: RequestInit): Promise<getApiDronesDroneIdResponse> => {
  
  const res = await fetch(getGetApiDronesDroneIdUrl(droneId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getApiDronesDroneIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiDronesDroneIdResponse
}



export type patchApiDronesDroneIdResponse200 = {
  data: DroneResponse
  status: 200
}
    
export type patchApiDronesDroneIdResponseSuccess = (patchApiDronesDroneIdResponse200) & {
  headers: Headers;
};
;

export type patchApiDronesDroneIdResponse = (patchApiDronesDroneIdResponseSuccess)

export const getPatchApiDronesDroneIdUrl = (droneId: string,) => {


  

  return `/api/drones/${droneId}`
}

export const patchApiDronesDroneId = async (droneId: string,
    updateDroneRequest: UpdateDroneRequest, options?: RequestInit): Promise<patchApiDronesDroneIdResponse> => {
  
  const res = await fetch(getPatchApiDronesDroneIdUrl(droneId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateDroneRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: patchApiDronesDroneIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as patchApiDronesDroneIdResponse
}



export type deleteApiDronesDroneIdResponse200 = {
  data: MessageResponse
  status: 200
}
    
export type deleteApiDronesDroneIdResponseSuccess = (deleteApiDronesDroneIdResponse200) & {
  headers: Headers;
};
;

export type deleteApiDronesDroneIdResponse = (deleteApiDronesDroneIdResponseSuccess)

export const getDeleteApiDronesDroneIdUrl = (droneId: string,) => {


  

  return `/api/drones/${droneId}`
}

export const deleteApiDronesDroneId = async (droneId: string, options?: RequestInit): Promise<deleteApiDronesDroneIdResponse> => {
  
  const res = await fetch(getDeleteApiDronesDroneIdUrl(droneId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: deleteApiDronesDroneIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteApiDronesDroneIdResponse
}



export type getIdResponse200 = {
  data: MaintenanceLogResponse
  status: 200
}
    
export type getIdResponseSuccess = (getIdResponse200) & {
  headers: Headers;
};
;

export type getIdResponse = (getIdResponseSuccess)

export const getGetIdUrl = (id: string,) => {


  

  return `/${id}`
}

export const getId = async (id: string, options?: RequestInit): Promise<getIdResponse> => {
  
  const res = await fetch(getGetIdUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getIdResponse
}



export type patchIdResponse200 = {
  data: MaintenanceLogResponse
  status: 200
}
    
export type patchIdResponseSuccess = (patchIdResponse200) & {
  headers: Headers;
};
;

export type patchIdResponse = (patchIdResponseSuccess)

export const getPatchIdUrl = (id: string,
    params?: PatchIdParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/${id}?${stringifiedParams}` : `/${id}`
}

export const patchId = async (id: string,
    params?: PatchIdParams, options?: RequestInit): Promise<patchIdResponse> => {
  
  const res = await fetch(getPatchIdUrl(id,params),
  {      
    ...options,
    method: 'PATCH'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: patchIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as patchIdResponse
}



export type deleteIdResponse200 = {
  data: MessageResponse
  status: 200
}
    
export type deleteIdResponseSuccess = (deleteIdResponse200) & {
  headers: Headers;
};
;

export type deleteIdResponse = (deleteIdResponseSuccess)

export const getDeleteIdUrl = (id: string,) => {


  

  return `/${id}`
}

export const deleteId = async (id: string, options?: RequestInit): Promise<deleteIdResponse> => {
  
  const res = await fetch(getDeleteIdUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: deleteIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteIdResponse
}



export type getDroneDroneIdResponse200 = {
  data: MaintenanceLogResponse[]
  status: 200
}
    
export type getDroneDroneIdResponseSuccess = (getDroneDroneIdResponse200) & {
  headers: Headers;
};
;

export type getDroneDroneIdResponse = (getDroneDroneIdResponseSuccess)

export const getGetDroneDroneIdUrl = (droneId: string,) => {


  

  return `/drone/${droneId}`
}

export const getDroneDroneId = async (droneId: string, options?: RequestInit): Promise<getDroneDroneIdResponse> => {
  
  const res = await fetch(getGetDroneDroneIdUrl(droneId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getDroneDroneIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getDroneDroneIdResponse
}



export type postApiOrdersResponse200 = {
  data: OrderResponse
  status: 200
}
    
export type postApiOrdersResponseSuccess = (postApiOrdersResponse200) & {
  headers: Headers;
};
;

export type postApiOrdersResponse = (postApiOrdersResponseSuccess)

export const getPostApiOrdersUrl = () => {


  

  return `/api/orders`
}

export const postApiOrders = async (createOrderRequest: CreateOrderRequest, options?: RequestInit): Promise<postApiOrdersResponse> => {
  
  const res = await fetch(getPostApiOrdersUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createOrderRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postApiOrdersResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postApiOrdersResponse
}



export type getApiOrdersResponse200 = {
  data: OrderResponse[]
  status: 200
}
    
export type getApiOrdersResponseSuccess = (getApiOrdersResponse200) & {
  headers: Headers;
};
;

export type getApiOrdersResponse = (getApiOrdersResponseSuccess)

export const getGetApiOrdersUrl = () => {


  

  return `/api/orders`
}

export const getApiOrders = async ( options?: RequestInit): Promise<getApiOrdersResponse> => {
  
  const res = await fetch(getGetApiOrdersUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getApiOrdersResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiOrdersResponse
}



export type getApiOrdersOrderIdResponse200 = {
  data: OrderResponse[]
  status: 200
}
    
export type getApiOrdersOrderIdResponseSuccess = (getApiOrdersOrderIdResponse200) & {
  headers: Headers;
};
;

export type getApiOrdersOrderIdResponse = (getApiOrdersOrderIdResponseSuccess)

export const getGetApiOrdersOrderIdUrl = (orderId: string,) => {


  

  return `/api/orders/${orderId}`
}

export const getApiOrdersOrderId = async (orderId: string, options?: RequestInit): Promise<getApiOrdersOrderIdResponse> => {
  
  const res = await fetch(getGetApiOrdersOrderIdUrl(orderId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getApiOrdersOrderIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiOrdersOrderIdResponse
}



export type postApiOrdersOrderIdCancelResponse200 = {
  data: MessageResponse
  status: 200
}
    
export type postApiOrdersOrderIdCancelResponseSuccess = (postApiOrdersOrderIdCancelResponse200) & {
  headers: Headers;
};
;

export type postApiOrdersOrderIdCancelResponse = (postApiOrdersOrderIdCancelResponseSuccess)

export const getPostApiOrdersOrderIdCancelUrl = (orderId: string,) => {


  

  return `/api/orders/${orderId}/cancel`
}

export const postApiOrdersOrderIdCancel = async (orderId: string, options?: RequestInit): Promise<postApiOrdersOrderIdCancelResponse> => {
  
  const res = await fetch(getPostApiOrdersOrderIdCancelUrl(orderId),
  {      
    ...options,
    method: 'POST'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postApiOrdersOrderIdCancelResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postApiOrdersOrderIdCancelResponse
}



export type postApiProductsResponse200 = {
  data: ProductResponse
  status: 200
}
    
export type postApiProductsResponseSuccess = (postApiProductsResponse200) & {
  headers: Headers;
};
;

export type postApiProductsResponse = (postApiProductsResponseSuccess)

export const getPostApiProductsUrl = () => {


  

  return `/api/products`
}

export const postApiProducts = async (createProductRequest: CreateProductRequest, options?: RequestInit): Promise<postApiProductsResponse> => {
  
  const res = await fetch(getPostApiProductsUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createProductRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postApiProductsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postApiProductsResponse
}



export type getApiProductsResponse200 = {
  data: ProductResponse[]
  status: 200
}
    
export type getApiProductsResponseSuccess = (getApiProductsResponse200) & {
  headers: Headers;
};
;

export type getApiProductsResponse = (getApiProductsResponseSuccess)

export const getGetApiProductsUrl = () => {


  

  return `/api/products`
}

export const getApiProducts = async ( options?: RequestInit): Promise<getApiProductsResponse> => {
  
  const res = await fetch(getGetApiProductsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getApiProductsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiProductsResponse
}



export type getApiProductsIdResponse200 = {
  data: ProductResponse
  status: 200
}
    
export type getApiProductsIdResponseSuccess = (getApiProductsIdResponse200) & {
  headers: Headers;
};
;

export type getApiProductsIdResponse = (getApiProductsIdResponseSuccess)

export const getGetApiProductsIdUrl = (id: string,) => {


  

  return `/api/products/${id}`
}

export const getApiProductsId = async (id: string, options?: RequestInit): Promise<getApiProductsIdResponse> => {
  
  const res = await fetch(getGetApiProductsIdUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getApiProductsIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiProductsIdResponse
}



export type patchApiProductsIdResponse200 = {
  data: ProductResponse
  status: 200
}
    
export type patchApiProductsIdResponseSuccess = (patchApiProductsIdResponse200) & {
  headers: Headers;
};
;

export type patchApiProductsIdResponse = (patchApiProductsIdResponseSuccess)

export const getPatchApiProductsIdUrl = (id: string,) => {


  

  return `/api/products/${id}`
}

export const patchApiProductsId = async (id: string,
    updateProductRequest: UpdateProductRequest, options?: RequestInit): Promise<patchApiProductsIdResponse> => {
  
  const res = await fetch(getPatchApiProductsIdUrl(id),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateProductRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: patchApiProductsIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as patchApiProductsIdResponse
}



export type deleteApiProductsIdResponse200 = {
  data: MessageResponse
  status: 200
}
    
export type deleteApiProductsIdResponseSuccess = (deleteApiProductsIdResponse200) & {
  headers: Headers;
};
;

export type deleteApiProductsIdResponse = (deleteApiProductsIdResponseSuccess)

export const getDeleteApiProductsIdUrl = (id: string,) => {


  

  return `/api/products/${id}`
}

export const deleteApiProductsId = async (id: string, options?: RequestInit): Promise<deleteApiProductsIdResponse> => {
  
  const res = await fetch(getDeleteApiProductsIdUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: deleteApiProductsIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteApiProductsIdResponse
}



export type getApiProductsCategoryCategoryIdResponse200 = {
  data: ProductResponse[]
  status: 200
}
    
export type getApiProductsCategoryCategoryIdResponseSuccess = (getApiProductsCategoryCategoryIdResponse200) & {
  headers: Headers;
};
;

export type getApiProductsCategoryCategoryIdResponse = (getApiProductsCategoryCategoryIdResponseSuccess)

export const getGetApiProductsCategoryCategoryIdUrl = (categoryId: number,) => {


  

  return `/api/products/category/${categoryId}`
}

export const getApiProductsCategoryCategoryId = async (categoryId: number, options?: RequestInit): Promise<getApiProductsCategoryCategoryIdResponse> => {
  
  const res = await fetch(getGetApiProductsCategoryCategoryIdUrl(categoryId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getApiProductsCategoryCategoryIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiProductsCategoryCategoryIdResponse
}



export type getApiProductsRestaurantRestaurantIdResponse200 = {
  data: ProductResponse[]
  status: 200
}
    
export type getApiProductsRestaurantRestaurantIdResponseSuccess = (getApiProductsRestaurantRestaurantIdResponse200) & {
  headers: Headers;
};
;

export type getApiProductsRestaurantRestaurantIdResponse = (getApiProductsRestaurantRestaurantIdResponseSuccess)

export const getGetApiProductsRestaurantRestaurantIdUrl = (restaurantId: string,) => {


  

  return `/api/products/restaurant/${restaurantId}`
}

export const getApiProductsRestaurantRestaurantId = async (restaurantId: string, options?: RequestInit): Promise<getApiProductsRestaurantRestaurantIdResponse> => {
  
  const res = await fetch(getGetApiProductsRestaurantRestaurantIdUrl(restaurantId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getApiProductsRestaurantRestaurantIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiProductsRestaurantRestaurantIdResponse
}



export type postApiRestaurantsResponse200 = {
  data: RestaurantResponse
  status: 200
}
    
export type postApiRestaurantsResponseSuccess = (postApiRestaurantsResponse200) & {
  headers: Headers;
};
;

export type postApiRestaurantsResponse = (postApiRestaurantsResponseSuccess)

export const getPostApiRestaurantsUrl = () => {


  

  return `/api/restaurants`
}

export const postApiRestaurants = async (createRestaurantRequest: CreateRestaurantRequest, options?: RequestInit): Promise<postApiRestaurantsResponse> => {
  
  const res = await fetch(getPostApiRestaurantsUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createRestaurantRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postApiRestaurantsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postApiRestaurantsResponse
}



export type getApiRestaurantsResponse200 = {
  data: RestaurantResponse[]
  status: 200
}
    
export type getApiRestaurantsResponseSuccess = (getApiRestaurantsResponse200) & {
  headers: Headers;
};
;

export type getApiRestaurantsResponse = (getApiRestaurantsResponseSuccess)

export const getGetApiRestaurantsUrl = () => {


  

  return `/api/restaurants`
}

export const getApiRestaurants = async ( options?: RequestInit): Promise<getApiRestaurantsResponse> => {
  
  const res = await fetch(getGetApiRestaurantsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getApiRestaurantsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiRestaurantsResponse
}



export type getApiRestaurantsIdResponse200 = {
  data: RestaurantResponse
  status: 200
}
    
export type getApiRestaurantsIdResponseSuccess = (getApiRestaurantsIdResponse200) & {
  headers: Headers;
};
;

export type getApiRestaurantsIdResponse = (getApiRestaurantsIdResponseSuccess)

export const getGetApiRestaurantsIdUrl = (id: string,) => {


  

  return `/api/restaurants/${id}`
}

export const getApiRestaurantsId = async (id: string, options?: RequestInit): Promise<getApiRestaurantsIdResponse> => {
  
  const res = await fetch(getGetApiRestaurantsIdUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getApiRestaurantsIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiRestaurantsIdResponse
}



export type patchApiRestaurantsIdResponse200 = {
  data: RestaurantResponse
  status: 200
}
    
export type patchApiRestaurantsIdResponseSuccess = (patchApiRestaurantsIdResponse200) & {
  headers: Headers;
};
;

export type patchApiRestaurantsIdResponse = (patchApiRestaurantsIdResponseSuccess)

export const getPatchApiRestaurantsIdUrl = (id: string,) => {


  

  return `/api/restaurants/${id}`
}

export const patchApiRestaurantsId = async (id: string,
    updateRestaurantRequest: UpdateRestaurantRequest, options?: RequestInit): Promise<patchApiRestaurantsIdResponse> => {
  
  const res = await fetch(getPatchApiRestaurantsIdUrl(id),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateRestaurantRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: patchApiRestaurantsIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as patchApiRestaurantsIdResponse
}



export type deleteApiRestaurantsIdResponse200 = {
  data: MessageResponse
  status: 200
}
    
export type deleteApiRestaurantsIdResponseSuccess = (deleteApiRestaurantsIdResponse200) & {
  headers: Headers;
};
;

export type deleteApiRestaurantsIdResponse = (deleteApiRestaurantsIdResponseSuccess)

export const getDeleteApiRestaurantsIdUrl = (id: string,) => {


  

  return `/api/restaurants/${id}`
}

export const deleteApiRestaurantsId = async (id: string, options?: RequestInit): Promise<deleteApiRestaurantsIdResponse> => {
  
  const res = await fetch(getDeleteApiRestaurantsIdUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: deleteApiRestaurantsIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteApiRestaurantsIdResponse
}



export type postApiReviewsResponse200 = {
  data: ReviewResponse
  status: 200
}
    
export type postApiReviewsResponseSuccess = (postApiReviewsResponse200) & {
  headers: Headers;
};
;

export type postApiReviewsResponse = (postApiReviewsResponseSuccess)

export const getPostApiReviewsUrl = () => {


  

  return `/api/reviews`
}

export const postApiReviews = async (createReviewRequest: CreateReviewRequest, options?: RequestInit): Promise<postApiReviewsResponse> => {
  
  const res = await fetch(getPostApiReviewsUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createReviewRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postApiReviewsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postApiReviewsResponse
}



export type getApiReviewsRestaurantRestaurantIdResponse200 = {
  data: ReviewResponse[]
  status: 200
}
    
export type getApiReviewsRestaurantRestaurantIdResponseSuccess = (getApiReviewsRestaurantRestaurantIdResponse200) & {
  headers: Headers;
};
;

export type getApiReviewsRestaurantRestaurantIdResponse = (getApiReviewsRestaurantRestaurantIdResponseSuccess)

export const getGetApiReviewsRestaurantRestaurantIdUrl = (restaurantId: string,) => {


  

  return `/api/reviews/restaurant/${restaurantId}`
}

export const getApiReviewsRestaurantRestaurantId = async (restaurantId: string, options?: RequestInit): Promise<getApiReviewsRestaurantRestaurantIdResponse> => {
  
  const res = await fetch(getGetApiReviewsRestaurantRestaurantIdUrl(restaurantId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getApiReviewsRestaurantRestaurantIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiReviewsRestaurantRestaurantIdResponse
}



export type patchApiReviewsReviewIdResponse200 = {
  data: ReviewResponse
  status: 200
}
    
export type patchApiReviewsReviewIdResponseSuccess = (patchApiReviewsReviewIdResponse200) & {
  headers: Headers;
};
;

export type patchApiReviewsReviewIdResponse = (patchApiReviewsReviewIdResponseSuccess)

export const getPatchApiReviewsReviewIdUrl = (reviewId: string,) => {


  

  return `/api/reviews/${reviewId}`
}

export const patchApiReviewsReviewId = async (reviewId: string,
    updateReviewRequest: UpdateReviewRequest, options?: RequestInit): Promise<patchApiReviewsReviewIdResponse> => {
  
  const res = await fetch(getPatchApiReviewsReviewIdUrl(reviewId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateReviewRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: patchApiReviewsReviewIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as patchApiReviewsReviewIdResponse
}



export type deleteApiReviewsReviewIdResponse200 = {
  data: MessageResponse
  status: 200
}
    
export type deleteApiReviewsReviewIdResponseSuccess = (deleteApiReviewsReviewIdResponse200) & {
  headers: Headers;
};
;

export type deleteApiReviewsReviewIdResponse = (deleteApiReviewsReviewIdResponseSuccess)

export const getDeleteApiReviewsReviewIdUrl = (reviewId: string,) => {


  

  return `/api/reviews/${reviewId}`
}

export const deleteApiReviewsReviewId = async (reviewId: string, options?: RequestInit): Promise<deleteApiReviewsReviewIdResponse> => {
  
  const res = await fetch(getDeleteApiReviewsReviewIdUrl(reviewId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: deleteApiReviewsReviewIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteApiReviewsReviewIdResponse
}
