/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Drones API
 * OpenAPI spec version: v1
 */

export interface CheckoutSessionResponse {
  orderId?: string;
  /** @nullable */
  sessionId?: string | null;
  /** @nullable */
  checkoutUrl?: string | null;
}
