/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Drones API
 * OpenAPI spec version: v1
 */

export interface CreateDroneRequest {
  /** @nullable */
  name?: string | null;
  maxPayloadKg?: number;
  homeLatitude?: number;
  homeLongitude?: number;
}
