/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Drones API
 * OpenAPI spec version: v1
 */

export interface CreateReviewRequest {
  restaurantId?: string;
  rating?: number;
  /** @nullable */
  comment?: string | null;
}
