/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Drones API
 * OpenAPI spec version: v1
 */
import type { OrderItemRequest } from './orderItemRequest';

export interface CreateOrderRequest {
  restaurantId?: string;
  /** @nullable */
  deliveryPointId?: string | null;
  /** @nullable */
  deliveryAddress?: string | null;
  deliveryLatitude?: number;
  deliveryLongitude?: number;
  /** @nullable */
  items?: OrderItemRequest[] | null;
}
