/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Drones API
 * OpenAPI spec version: v1
 */

export interface DroneResponse {
  id?: string;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  status?: string | null;
  batteryLevel?: number;
  maxPayloadKg?: number;
  currentLatitude?: number;
  currentLongitude?: number;
  /** @nullable */
  lastSeenAt?: string | null;
  createdAt?: string;
}
