/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Drones API
 * OpenAPI spec version: v1
 */

export interface ForgotPasswordRequest {
  /** @nullable */
  email?: string | null;
  /** @nullable */
  clientApp?: string | null;
}
