/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Drones API
 * OpenAPI spec version: v1
 */

export interface OrderItemRequest {
  /** @nullable */
  productName?: string | null;
  quantity?: number;
  unitPrice?: number;
}
