/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Drones API
 * OpenAPI spec version: v1
 */

export interface PaymentStatusResponse {
  orderId?: string;
  /** @nullable */
  orderStatus?: string | null;
  /** @nullable */
  paymentStatus?: string | null;
  amount?: number;
  /** @nullable */
  currency?: string | null;
}
