/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Drones API
 * OpenAPI spec version: v1
 */

export interface RestaurantApplicationResponse {
  id?: string;
  userId?: string;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  companyName?: string | null;
  /** @nullable */
  taxId?: string | null;
  /** @nullable */
  contactPhone?: string | null;
  /** @nullable */
  restaurantName?: string | null;
  /** @nullable */
  address?: string | null;
  latitude?: number;
  longitude?: number;
  /** @nullable */
  description?: string | null;
  openTime?: string;
  closeTime?: string;
  /** @nullable */
  status?: string | null;
  /** @nullable */
  adminNote?: string | null;
  createdAt?: string;
  /** @nullable */
  reviewedAt?: string | null;
  /** @nullable */
  restaurantId?: string | null;
}
