/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Drones API
 * OpenAPI spec version: v1
 */

export interface ReviewRestaurantApplicationRequest {
  /** @nullable */
  adminNote?: string | null;
}
