/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Drones API
 * OpenAPI spec version: v1
 */

export interface UpdateReviewRequest {
  rating?: number;
  /** @nullable */
  comment?: string | null;
}
