/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Drones API
 * OpenAPI spec version: v1
 */

export interface UpdateDroneRequest {
  /** @nullable */
  name?: string | null;
  /** @nullable */
  maxPayloadKg?: number | null;
  /** @nullable */
  batteryLevel?: number | null;
}
