/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Drones API
 * OpenAPI spec version: v1
 */

export interface UserDto {
  id?: string;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  roles?: string[] | null;
}
