/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Drones API
 * OpenAPI spec version: v1
 */
import type { UserDto } from './userDto';

export interface AuthResponse {
  /** @nullable */
  accessToken?: string | null;
  /** @nullable */
  refreshToken?: string | null;
  accessTokenExpiresAt?: string;
  user?: UserDto;
}
