/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Drones API
 * OpenAPI spec version: v1
 */

export interface CreateDeliveryPointRequest {
  /** @nullable */
  name?: string | null;
  /** @nullable */
  address?: string | null;
  latitude?: number;
  longitude?: number;
  isActive?: boolean;
}
