/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Drones API
 * OpenAPI spec version: v1
 */

export interface CreateRestaurantRequest {
  /** @nullable */
  name?: string | null;
  /** @nullable */
  address?: string | null;
  latitude?: number;
  longitude?: number;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  imageUrl?: string | null;
  openTime?: string;
  closeTime?: string;
}
