/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Drones API
 * OpenAPI spec version: v1
 */

export interface CreateDispatchRequest {
  orderId?: string;
  /** @nullable */
  droneId?: string | null;
}
