/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Drones API
 * OpenAPI spec version: v1
 */
import type { DroneRoutePointResponse } from './droneRoutePointResponse';

export interface DroneFlightHistoryResponse {
  dispatchId?: string;
  orderId?: string;
  droneId?: string;
  /** @nullable */
  status?: string | null;
  /** @nullable */
  deliveryAddress?: string | null;
  createdAt?: string;
  /** @nullable */
  estimatedDeliveryAt?: string | null;
  /** @nullable */
  deliveredAt?: string | null;
  /** @nullable */
  routePoints?: DroneRoutePointResponse[] | null;
}
