/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Drones API
 * OpenAPI spec version: v1
 */

export interface DroneRoutePointResponse {
  latitude?: number;
  longitude?: number;
  batteryLevel?: number;
  recordedAt?: string;
}
