/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Drones API
 * OpenAPI spec version: v1
 */

export interface OrderItemResponse {
  id?: string;
  productId?: string;
  /** @nullable */
  productName?: string | null;
  quantity?: number;
  unitPrice?: number;
}
