/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Drones API
 * OpenAPI spec version: v1
 */

export interface RegisterRestaurantOwnerRequest {
  /** @nullable */
  email?: string | null;
  /** @nullable */
  password?: string | null;
  /** @nullable */
  confirmPassword?: string | null;
  /** @nullable */
  clientApp?: string | null;
  /** @nullable */
  companyName?: string | null;
  /** @nullable */
  taxId?: string | null;
  /** @nullable */
  contactPhone?: string | null;
  /** @nullable */
  restaurantName?: string | null;
  /** @nullable */
  address?: string | null;
  latitude?: number;
  longitude?: number;
  /** @nullable */
  description?: string | null;
  openTime?: string;
  closeTime?: string;
}
