/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Drones API
 * OpenAPI spec version: v1
 */

export interface ResetPasswordRequest {
  /** @nullable */
  token?: string | null;
  /** @nullable */
  newPassword?: string | null;
  /** @nullable */
  confirmPassword?: string | null;
}
