/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Drones API
 * OpenAPI spec version: v1
 */

export interface ReviewResponse {
  id?: string;
  userId?: string;
  /** @nullable */
  userEmail?: string | null;
  restaurantId?: string;
  rating?: number;
  /** @nullable */
  comment?: string | null;
  createdAt?: string;
  /** @nullable */
  updatedAt?: string | null;
}
