/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Drones API
 * OpenAPI spec version: v1
 */

export interface UpdateReviewRequest {
  rating?: number;
  /** @nullable */
  comment?: string | null;
}
