/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Drones API
 * OpenAPI spec version: v1
 */

export interface UpdateRestaurantRequest {
  /** @nullable */
  name?: string | null;
  /** @nullable */
  address?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  imageUrl?: string | null;
  /** @nullable */
  isOpen?: boolean | null;
  /** @nullable */
  openTime?: string | null;
  /** @nullable */
  closeTime?: string | null;
}
