/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Drones API
 * OpenAPI spec version: v1
 */

export interface UpdateMaintenanceLogRequest {
  /** @nullable */
  notes?: string | null;
  /** @nullable */
  performedAt?: string | null;
}
